### ISSUE TITLE
Other colours?

### ISSUE THREAD

**Issue by peternewman** [gobo-ws/ola-trigger-ikea-tradfri-dmx#1]
Out of interest have you tried other colours, they appear to correspond to HTML/Hex codes, or are there only three discrete white LEDs in the unit?

**Comment by gobo-ws** [comment]
Hi @peternewman
Default color temperature is 2700K and the Trådfri app and remote control only have three white color temperature options (2200K, 2700K and 4000K)
I have not tested it myself but it should be possible. The lamps supports the white spectrum between 2200-4000K. 
I will probably add more colors to the config in the future.

**Comment by peternewman** [comment]
Cool, I was particularly curious if it was using the HTML colour codes to be helpful, or if they actually corresponded to the direct colour it was outputting.
