### ISSUE TITLE
Tradfri API changes

### ISSUE THREAD

**Issue by peternewman** [gobo-ws/ola-trigger-ikea-tradfri-dmx#2]
FYI:
https://twitter.com/home_assistant/status/925373865802502144

**Comment by gobo-ws** [comment]
Thanks for the information Peter!

**Comment by gobo-ws** [comment]
https://github.com/ggravlingen/pytradfri/issues/90

**Comment by gobo-ws** [comment]
Register a new user and get a pre shared key from the gateway works fine.
The following command to check the status of a bulb also works fine:
`$ coap-client -m get -u "NEW_USER" -k "NEW_PSK" "coaps://10.50.30.44:5684/15001/65538"`

Output:
> v:1 t:CON c:GET i:f447 {} [ ]
> {"9001":"test","9002":1509720835,"9020":1509720853,"9003":65538,"9054":0,"5750":2,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E27 WS opal 980lm","2":"","3":"1.2.217","6":1},"3311":[{"5850":1,"5851":66,"5711":450,"5709":32886,"5710":27217,"5706":"efd275","9003":0}]}

But I can't control the bulb. Not on/off, brightness or color temperature.
The following command should work to turn off the bulb but it does not.
`coap-client -m put -u "USERNAME" -k "PSK" -e '{ "3311" : [{ "5850" : 0 ]} }' "coaps://IP:5684/15001/65538"`

But I just got back a 4.00 response:
> v:1 t:CON c:PUT i:83c3 {} [ ]
> 4.00

Need some more testing...

**Comment by gobo-ws** [comment]
`coap-client -m put -u "USERNAME" -k "PSK" -e '{ "3311": [{ "5850": 0 }] }' "coaps://IP:5684/15001/65537"` works. Will update the config and shell script later on.

**Comment by gobo-ws** [comment]
I have now updated the files so it works with the new API changes.

**Comment by peternewman** [comment]
Cool @gobo-ws . I was going to say can you update this in OLA, but I see it hasn't made it in yet, so do you fancy adding it?

**Comment by gobo-ws** [comment]
@peternewman I have not thought about it because the trigger config needs the shell script as well. But it may not be a problem? Maybe we should have some type of library for OLA trigger configs?

**Comment by peternewman** [comment]
We could add the shell script to the repo too @gobo-ws . In some ways it will help as a more complex example for people to look at.

Funny you should say that about the library, we don't currently ship the examples with Debian, but could do so, possibly in one package for the standalone ones, and maybe even a seperate package that's Recommended by the main one which Depends coap-client, so you apt-get install ola-trigger-ikea-tradfri or whatever and it pulls in everything you need to make it work. What do you think @yoe ?

**Comment by yoe** [comment]
Sorry, forgot to reply to this one.

Yup, I can ship examples. Usually they'd go into `/usr/share/doc/<package>`. Which package that would be depends on the type of package; e.g., examples to use an API would go into a -dev package, whereas examples to use a command-line tool would go into the package that contains the tool or its documentation.

What kind of examples are we talking about?

**Comment by peternewman** [comment]
Thanks @yoe I wasn't sure if you'd get the notification . They're examples for our CLI tool ola_trigger ( http://docs.openlighting.org/ola/man/man1/ola_trigger.1.html ).

The other existing ones are in here:
https://github.com/OpenLightingProject/ola/tree/master/tools/ola_trigger/contrib

Aside from the one we're discussing, they're generally just a config file, although this one has an associated shell script too. It's normal to just ship this kind of thing as a config example then, rather than as a (potentially standalone package), which pulls in all the necessary dependencies (e.g. curl etc) to "Just Work" (probably with some IP config)? I don't know if it's worth shipping the Mac ones as further examples or not?

Sorry for hijacking your issue tracker @gobo-ws , although they're mostly your example configs.
